hpc=read.table("household_power_consumption.txt", sep=";", col.names=c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"), colClasses=c("character", "character", "numeric","numeric","numeric","numeric","numeric","numeric","numeric"), na.strings="?", skip=1)
hpc=subset(hpc, hpc$Date=="1/2/2007" | hpc$Date=="2/2/2007")
hpc$Date=as.Date(hpc$Date, "%d/%m/%Y")
png("plot1.png", width = 480, height = 480)
hist(hpc$Global_active_power, xlab="Global Active Power (kilowatts)", main="Global Active Power", col="orangered", ylim=c(0, 1200))
yticks=seq(200,600,1200)
axis(2, at=yticks)
dev.off()