hpc=read.table("household_power_consumption.txt", sep=";", col.names=c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"), colClasses=c("character", "character", "numeric","numeric","numeric","numeric","numeric","numeric","numeric"), na.strings="?", skip=1)
hpc=subset(hpc, hpc$Date=="1/2/2007" | hpc$Date=="2/2/2007")
hpc$Date=as.Date(hpc$Date, "%d/%m/%Y")
hpc$datetime=paste(hpc$Date, hpc$Time)
hpc$datetime=strptime(hpc$datetime, "%Y-%m-%d %H:%M:%S")
png("plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(hpc$datetime, hpc$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(hpc$datetime, hpc$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(hpc$datetime, hpc$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
points(hpc$datetime, hpc$Sub_metering_2, type="l", col="red")
points(hpc$datetime, hpc$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lwd=2 , box.lwd = 0)
plot(hpc$datetime, hpc$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()